site_name: Definitely Not Java
site_url: https://dylan-liew.github.io/definitely-not-java/
use_directory_urls: true

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - 0. Home: 'index.md'
  - 1. Java Fundamentals: '01-java-fundamentals.md'
  - 2. OOP Basics: '02-oop-basics.md'
  - 3. Class Structure: '03-class-structure.md'
  - 4. Inheritance & Polymorphism: '04-inheritance-polymorphism.md'
  - 5. Interfaces & Abstract Classes: '05-interfaces-abstract.md'
  - 6. Exceptions & Wrappers: '06-exceptions-wrappers.md'
  - 7. Generics: '07-generics.md'
  - 8. Functional Programming: '08-functional-programming.md'
  - 9. Concurrency: '09-concurrency.md'
  - 10. Advanced Topics: '10-advanced-topics.md'
theme:
  name: material
  logo: assets/dlogo.png 
  favicon: assets/dlogo.png 
  features:
    - navigation.instant
    - navigation.sections 
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: white
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - assets/custom.css
